# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: "Documenation"
description: "A simple guide that tells about my interests and activites. Thigs I love and things I do and Things i want to do."

# Author's info
author: 'Divyanshu Mehta'
# edit 'categories' in the front matter of every post to match this username
nickname: divyanshumehta
bio: 'Compter Geek,  Cinephile, Gamer'
location: 'Patna, India'
url: 'https://github.com/divyanshumehta'
image: 'assets/images/dm.jpg'

short_url: 'https://github.com/divyanshumehta'
# google_analytics: UA-69281367-1
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /
# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: divyanshumehta
repo: divyanshumehta.github.io
branch: master
# relative_source: ../jasper/
# destination: ../jasper-pages/
# production_url:  https://biomadeira.github.io/jasper/
# source_url:      https://github.com/biomadeira/jasper/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
